<?php $integrationId = $block->getIntegrationId(); ?>
<div class="action">
    <button class="button run-integration"><?=__('Run Integration')?></button>
</div>

<script>
    require([
        'jquery',
        'jquery/ui'
    ], function ($) {
        'use strict';

        const ajaxUrl = "<?=$this->getUrl('integration/integration/run', ['id' => $integrationId])?>";
        // @todo Implement selected stores
        const selectedStores = '';

        $('.run-integration').on('click', function () {

            if ($('.process-response-block').length) {
                $('.process-response-block').remove();
            }
            $("body").trigger('processStart');
            $.ajax({
                context: '#process-response',
                url: ajaxUrl,
                dataType: 'json',
                type: 'get',
                data: {},
            }).done(function (data) {
                $("body").trigger('processStop');
                if (data) {
                    $('.action').prepend('<div class="process-response-block"></div>');
                    data.each(function(el){
                        $('.process-response-block').append('<div class="process-progress-row">' + el + '</div>');
                    });
                }
                return true;
            });
        });
    });
</script>
